// <auto-generated />
using System;
using DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216193636_RemovePasswordHashFromSeedData")]
    partial class RemovePasswordHashFromSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-STAMP-STATIC-001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@techstore.com",
                            EmailConfirmed = true,
                            FullName = "System Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TECHSTORE.COM",
                            NormalizedUserName = "ADMIN@TECHSTORE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ADMIN-SECURITY-STAMP-STATIC-001",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "admin@techstore.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CUSTOMER-CONCURRENCY-STAMP-STATIC-002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "customer@example.com",
                            EmailConfirmed = true,
                            FullName = "Mostafa Zain",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER@EXAMPLE.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CUSTOMER-SECURITY-STAMP-STATIC-002",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "customer@example.com"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "/images/brands/apple.png",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "/images/brands/samsung.png",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "/images/brands/dell.png",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "/images/brands/hp.png",
                            Name = "HP"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "/images/brands/lenovo.png",
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 6,
                            LogoUrl = "/images/brands/asus.png",
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = 7,
                            LogoUrl = "/images/brands/acer.png",
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 8,
                            LogoUrl = "/images/brands/microsoft.png",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 9,
                            LogoUrl = "/images/brands/sony.png",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 10,
                            LogoUrl = "/images/brands/xiaomi.png",
                            Name = "Xiaomi"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("DAL.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasAnnotation("MinValue", 1);

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId", "CartId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fas fa-laptop",
                            Name = "Laptops",
                            Slug = "laptops"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fas fa-mobile-alt",
                            Name = "Smartphones",
                            Slug = "smartphones"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fas fa-headphones",
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fas fa-tablet-alt",
                            Name = "Tablets",
                            Slug = "tablets"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "fas fa-gamepad",
                            Name = "Gaming",
                            Slug = "gaming"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gaming Laptops",
                            ParentCategoryId = 1,
                            Slug = "gaming-laptops"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Business Laptops",
                            ParentCategoryId = 1,
                            Slug = "business-laptops"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ultrabooks",
                            ParentCategoryId = 1,
                            Slug = "ultrabooks"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Android Phones",
                            ParentCategoryId = 2,
                            Slug = "android-phones"
                        },
                        new
                        {
                            Id = 10,
                            Name = "iPhones",
                            ParentCategoryId = 2,
                            Slug = "iphones"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Headphones",
                            ParentCategoryId = 3,
                            Slug = "headphones"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Keyboards & Mice",
                            ParentCategoryId = 3,
                            Slug = "keyboards-mice"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cases & Covers",
                            ParentCategoryId = 3,
                            Slug = "cases-covers"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Powerful gaming laptop featuring AMD Ryzen 9 processor, NVIDIA RTX 4060 graphics, 16GB RAM, and 512GB SSD. 15.6-inch 144Hz display for smooth gameplay.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Buy ASUS ROG Strix G15 gaming laptop with RTX 4060 graphics card",
                            MetaTitle = "ASUS ROG Strix G15 Gaming Laptop",
                            Name = "ASUS ROG Strix G15",
                            OldPrice = 1499.99m,
                            Price = 1299.99m,
                            ShortDescription = "High-performance gaming laptop with RTX 4060",
                            Slug = "asus-rog-strix-g15",
                            StockQuantity = 25,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 7,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Intel Core i7, RTX 4050, 16GB DDR5 RAM, 512GB NVMe SSD. 15.6-inch FHD 165Hz display with excellent cooling system.",
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Affordable gaming laptop with great performance",
                            MetaTitle = "Acer Predator Helios 300 Gaming Laptop",
                            Name = "Acer Predator Helios 300",
                            OldPrice = 1299.99m,
                            Price = 1099.99m,
                            ShortDescription = "Affordable gaming powerhouse",
                            Slug = "acer-predator-helios-300",
                            StockQuantity = 30,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Intel Core i5-11th Gen, 8GB RAM, 256GB SSD. 14-inch FHD display with enterprise-level security features.",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsHot = false,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Professional Dell Latitude laptop for business users",
                            MetaTitle = "Dell Latitude 5420 Business Laptop",
                            Name = "Dell Latitude 5420",
                            OldPrice = 0m,
                            Price = 899.99m,
                            ShortDescription = "Professional business laptop",
                            Slug = "dell-latitude-5420",
                            StockQuantity = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Intel Core i7-11th Gen, 16GB RAM, 512GB SSD. 14-inch FHD touch display with premium build quality.",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsHot = false,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Premium HP EliteBook for professionals",
                            MetaTitle = "HP EliteBook 840 G8 Business Laptop",
                            Name = "HP EliteBook 840 G8",
                            OldPrice = 1399.99m,
                            Price = 1199.99m,
                            ShortDescription = "Premium business ultrabook",
                            Slug = "hp-elitebook-840-g8",
                            StockQuantity = 20,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple M3 chip, 8GB unified memory, 256GB SSD. 13.6-inch Liquid Retina display with exceptional battery life.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Latest MacBook Air with M3 chip",
                            MetaTitle = "MacBook Air M3 - Ultra-thin Laptop",
                            Name = "MacBook Air M3",
                            OldPrice = 0m,
                            Price = 1099.99m,
                            ShortDescription = "Ultra-thin and powerful",
                            Slug = "macbook-air-m3",
                            StockQuantity = 50,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Intel Core i7-13th Gen, 16GB RAM, 512GB SSD. 13.4-inch InfinityEdge FHD+ display in compact design.",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Premium Dell XPS 13 with stunning display",
                            MetaTitle = "Dell XPS 13 Ultrabook",
                            Name = "Dell XPS 13",
                            OldPrice = 1499.99m,
                            Price = 1299.99m,
                            ShortDescription = "Premium Windows ultrabook",
                            Slug = "dell-xps-13",
                            StockQuantity = 35,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CategoryId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.1-inch Super Retina XDR display, A17 Pro chip, 128GB storage, titanium design, advanced camera system.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Buy iPhone 15 Pro with A17 Pro chip",
                            MetaTitle = "iPhone 15 Pro - Latest Apple Smartphone",
                            Name = "iPhone 15 Pro",
                            OldPrice = 0m,
                            Price = 999.99m,
                            ShortDescription = "Titanium design with A17 Pro chip",
                            Slug = "iphone-15-pro",
                            StockQuantity = 100,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CategoryId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.1-inch Super Retina XDR display, A16 Bionic chip, 128GB storage, dual camera system.",
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Buy iPhone 15 with Dynamic Island",
                            MetaTitle = "iPhone 15 - Latest Apple Smartphone",
                            Name = "iPhone 15",
                            OldPrice = 0m,
                            Price = 799.99m,
                            ShortDescription = "The latest iPhone with Dynamic Island",
                            Slug = "iphone-15",
                            StockQuantity = 120,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.8-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 3, 12GB RAM, 256GB storage, 200MP camera, S Pen included.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Premium Samsung Galaxy S24 Ultra with S Pen",
                            MetaTitle = "Samsung Galaxy S24 Ultra Smartphone",
                            Name = "Samsung Galaxy S24 Ultra",
                            OldPrice = 0m,
                            Price = 1199.99m,
                            ShortDescription = "Ultimate flagship Android phone",
                            Slug = "samsung-galaxy-s24-ultra",
                            StockQuantity = 60,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 10,
                            CategoryId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.73-inch AMOLED display, Snapdragon 8 Gen 3, 12GB RAM, 256GB storage, Leica triple camera system.",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Xiaomi 14 Pro with Leica camera system",
                            MetaTitle = "Xiaomi 14 Pro Smartphone",
                            Name = "Xiaomi 14 Pro",
                            OldPrice = 999.99m,
                            Price = 899.99m,
                            ShortDescription = "Flagship killer with Leica camera",
                            Slug = "xiaomi-14-pro",
                            StockQuantity = 45,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "12.9-inch Liquid Retina XDR display, M2 chip, 128GB storage, Apple Pencil support, professional performance.",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsHot = false,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "iPad Pro 12.9 with M2 chip for professionals",
                            MetaTitle = "iPad Pro 12.9 inch - Professional Tablet",
                            Name = "iPad Pro 12.9\"",
                            OldPrice = 0m,
                            Price = 1099.99m,
                            ShortDescription = "Ultimate iPad with M2 chip",
                            Slug = "ipad-pro-12-9",
                            StockQuantity = 40,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "11-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, 8GB RAM, 128GB storage, S Pen included.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = false,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Premium Samsung tablet with S Pen",
                            MetaTitle = "Samsung Galaxy Tab S9 Tablet",
                            Name = "Samsung Galaxy Tab S9",
                            OldPrice = 899.99m,
                            Price = 799.99m,
                            ShortDescription = "Premium Android tablet",
                            Slug = "samsung-galaxy-tab-s9",
                            StockQuantity = 55,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 9,
                            CategoryId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Premium wireless headphones with exceptional noise cancellation, 30-hour battery life, superior sound quality.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Premium Sony headphones with noise cancellation",
                            MetaTitle = "Sony WH-1000XM5 Wireless Headphones",
                            Name = "Sony WH-1000XM5",
                            OldPrice = 0m,
                            Price = 399.99m,
                            ShortDescription = "Industry-leading noise cancellation",
                            Slug = "sony-wh-1000xm5",
                            StockQuantity = 80,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            CategoryId = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Active noise cancellation, adaptive transparency, personalized spatial audio with H2 chip.",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsHot = true,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Apple AirPods Pro with active noise cancellation",
                            MetaTitle = "AirPods Pro 2nd Generation",
                            Name = "Apple AirPods Pro (2nd Gen)",
                            OldPrice = 0m,
                            Price = 249.99m,
                            ShortDescription = "Premium wireless earbuds",
                            Slug = "apple-airpods-pro-2",
                            StockQuantity = 150,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 6,
                            CategoryId = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "ROG NX mechanical switches, RGB lighting, dedicated media controls, USB passthrough.",
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsHot = false,
                            MainImage = "/Images/placeholder.png",
                            MetaDescription = "Mechanical gaming keyboard with RGB lighting",
                            MetaTitle = "ASUS ROG Strix Scope II Gaming Keyboard",
                            Name = "ASUS ROG Strix Scope II Gaming Keyboard",
                            OldPrice = 179.99m,
                            Price = 149.99m,
                            ShortDescription = "Mechanical gaming keyboard",
                            Slug = "asus-rog-strix-scope-ii",
                            StockQuantity = 70,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DAL.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/products/asus-rog-strix-g15-1.jpg",
                            ProductId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/products/asus-rog-strix-g15-2.jpg",
                            ProductId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/products/iphone-15-pro-1.jpg",
                            ProductId = 7,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/products/sony-wh-1000xm5-1.jpg",
                            ProductId = 13,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating_Range", "Rating >= 1 AND Rating <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Runs everything smoothly. Great build quality.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsApproved = true,
                            ProductId = 1,
                            Rating = 5,
                            Title = "Excellent performance",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Camera is fantastic, battery life is solid.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsApproved = true,
                            ProductId = 7,
                            Rating = 4,
                            Title = "Great phone",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<string>("SpecKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SpecValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            SortOrder = 1,
                            SpecKey = "CPU",
                            SpecValue = "AMD Ryzen 9"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            SortOrder = 2,
                            SpecKey = "GPU",
                            SpecValue = "NVIDIA RTX 4060"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 7,
                            SortOrder = 1,
                            SpecKey = "Display",
                            SpecValue = "6.1-inch Super Retina XDR"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 7,
                            SortOrder = 2,
                            SpecKey = "Chip",
                            SpecValue = "A17 Pro"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ROLE-ADMIN-CONCURRENCY-STAMP-001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "ROLE-CUSTOMER-CONCURRENCY-STAMP-002",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Entities.Cart", b =>
                {
                    b.HasOne("DAL.Entities.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("DAL.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.CartItem", b =>
                {
                    b.HasOne("DAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.HasOne("DAL.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.HasOne("DAL.Entities.Brand", "ParentBrand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Category", "ParentCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentBrand");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DAL.Entities.ProductImage", b =>
                {
                    b.HasOne("DAL.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DAL.Entities.Review", b =>
                {
                    b.HasOne("DAL.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Specification", b =>
                {
                    b.HasOne("DAL.Entities.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
